### ISSUE TITLE
Pod exec doesn't default _request_timeout properly

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#1085] opened 2020-02-19 21:52 UTC
**What happened (please include outputs or screenshots)**:
When I run [pod exec stream](https://github.com/kubernetes-client/python/blob/f493272827ed31575b87a522a4206f446a1e12f6/examples/pod_exec.py#L74-L80) without specifying `_request_timeout`, `_request_timeout` gets defaulted to None.

**What you expected to happen**:
`_request_timeout` should be defaulted to 60 according to [the code](https://github.com/kubernetes-client/python-base/blob/a25f49eb41a28b5ffafb309f26e182b80ec747de/stream/ws_client.py#L278-L279)

**How to reproduce it (as minimally and precisely as possible)**:
Print kwargs before [this code](https://github.com/kubernetes-client/python-base/blob/a25f49eb41a28b5ffafb309f26e182b80ec747de/stream/ws_client.py#L278-L279) and run [this example](https://github.com/kubernetes-client/python/blob/f493272827ed31575b87a522a4206f446a1e12f6/examples/pod_exec.py#L74-L80). You can find `_preload_content` is set to None already. As a result, the following defaulting doesn't happen. 
```
{'body': None, 'query_params': [('command', ['/bin/sh', '-c', 'echo This message goes to stderr; echo This message goes to stdout']), ('stderr', True), ('stdin', False), ('stdout', True), ('tty', False)], 'post_params': [], '_request_timeout': None, '_preload_content': True, 'headers': {'Accept': '*/*', 'User-Agent': 'OpenAPI-Generator/11.0.0b2/python'}}
```

**Environment**:
- Kubernetes version (`kubectl version`): HEAD
- Python client version (`pip list | grep kubernetes`): 11.0.0b2

**Comment by Amyth07** [comment] 2020-04-18 15:16
Hey @roycaihw , Can you assign it to me?

**Comment by Amyth07** [comment] 2020-04-18 15:19
The issue is with the kwargs as it has _request_timeout  value is None. In that case, It won't go for the fallback back i.e 60.
It will go for 60  only if key  _request_timeout is present in kwargs.

**Closed** 2020-09-15 17:10 UTC
Labels: help wanted, kind/bug, lifecycle/rotten
