### ISSUE TITLE
watch loses resource version when watching custom object list

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes-client/python#700] opened 2018-12-11 07:58 UTC
kubernetes often resets watches when no changes happen (https://github.com/kubernetes/kubernetes/issues/55230#issuecomment-342632961), thus I have added a restart at the last resource version to my application

But the python api library resets this to zero on iteration of this loop and thus retrieves all objects again.
https://github.com/kubernetes-client/python-base/blob/83ebb9d5fdc0d46bbb2e30afcd8eec42c5da4ad1/watch/watch.py
This happens in current master using the list_cluster_custom_object function as a watch running against kubernetes 1.12.3.

Can this please be updated to respect the resource version set by the application or fix that it resets to version zero each time.

**Comment by juliantaylor** [comment] 2018-12-11 08:10
reproducing script:

```
import kubernetes as k8s
k8s.config.load_kube_config()
api = k8s.client.CustomObjectsApi()
group = "crd.mycustom.org"
plural = "mycustom"
version = "v1"
items = api.list_cluster_custom_object(group=group, plural=plural, version=version)
ver = items["metadata"]["resourceVersion"]

kwargs = {}
kwargs["resource_version"] = ver
kwargs["watch"] = 'true'
for event in k8s.watch.Watch().stream(api.list_cluster_custom_object, group, version, plural, **kwargs):
    print(event.name, event.metadata["resourceVersion"])
```

Run with printing the resource version in `kubernetes/client/apis/custom_objects_api.py `list_cluster_custom_object_with_http_info`

```
[('resourceVersion', '1209375'), ('watch', True)] # correct first watch
[('resourceVersion', 0), ('watch', True)] # incorrect version on first reset
```

**Comment by max-rocket-internet** [comment] 2018-12-11 08:43
probably a duplicate of what issue? You've linked back to this one. Maybe you meant https://github.com/kubernetes-client/python/issues/693 ?

**Comment by juliantaylor** [comment] 2018-12-11 08:49
fixed and updated the reproducer with manifests

**Closed** 2019-01-23 21:10 UTC
