### ISSUE TITLE
kubeconfig---user: exec!!!cannot pass auth

### ISSUE THREAD

**Issue by zhuhesheng** [kubernetes-client/python#552] opened 2018-06-20 04:53 UTC
in kubeconfig:
***
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "test"
Err : HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions is forbidden: User \"system:anonymous\" cannot list deployments.extensions at the cluster scope","reason":"Forbidden","details":{"group":"extensions","kind":"deployments"},"code":403}

**Comment by jgrigd** [comment] 2018-06-27 12:53
Duplicate of #514 which is not yet resolved.

**Closed** 2019-06-23 11:13 UTC
Labels: lifecycle/rotten
