### ISSUE TITLE
Upgrade request required when running exec command with python-kubernetes client

### ISSUE THREAD

**Issue by genadic** [kubernetes-client/python#409] opened 2017-12-05 15:37 UTC
I saw this image already appeared in https://github.com/kubernetes-incubator/client-python/issues/58 and was solved, but now it's broken again in 4.0

**Comment by dulek** [comment] 2017-12-05 15:40
I was looking at that as well, so here's some additional info:

#58 was fixed by #120, but @dims code is now gone due to commit #353.

**Comment by dims** [comment] 2017-12-05 16:01
hmmmmmmm....

**Comment by dims** [comment] 2017-12-05 16:02
@dulek do you have some time to re-patch please? i thought i had tests in there

**Comment by dulek** [comment] 2017-12-05 17:09
@dism: I can try. Those tests were disabled by #259.

**Comment by dulek** [comment] 2017-12-05 17:41
#410 is the commit. I was however unable to verify it as connection is now failing with "Reason: Handshake status 404".

**Comment by TopherGopher** [comment] 2018-07-06 13:59
Is there any status update on this? Has anyone figured out a workaround?
I don't mind patching this, but I don't understand why that massive pull request wiped out this logic. Was it because it was bad logic? Or was it just a merge mistake?

**Comment by pearsontophergopher** [comment] 2018-07-06 14:54
I found this issue mentioned (and apparently solved) over here: https://github.com/kubernetes-client/python/issues/526

`resp = kubernetes.stream.stream(self.core_api_instance.connect_get_namespaced_pod_exec, name,
namespace,command=exec_command1, stderr=True, stdin=False, stdout=True, tty=False)`

You can then manipulate that pipe using [the technique from the example code](https://github.com/kubernetes-client/python/blob/master/examples/exec.py#L61)

My issue is that I'm still getting an error message when I run it inside a pod in the cluster - 
```
>>> resp = k.stream.stream(k8s.connect_get_namespaced_pod_attach, 'datadog-agent-8pkwh', container="datadog-agent", namespace="default", stderr=True, stdin=False, stdout=True, tty=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 32, in stream
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 711, in connect_get_namespaced_pod_attach
    (data) = self.connect_get_namespaced_pod_attach_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 808, in connect_get_namespaced_pod_attach_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 27, in _intercept_request_call
    return ws_client.websocket_call(config, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/stream/ws_client.py", line 255, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: hostname '10.100.0.1' doesn't match either of 'ip-10-0-113-207.us-west-2.compute.internal', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local', '0e23207807f30610a20a7dc08f349bad.sk1.us-west-2.eks.amazonaws.com'
```
I'll let you know if I find the fix ;-)

**Comment by pearsontophergopher** [comment] 2018-07-06 19:47
The fix was I upgraded from Python 2 to Python 3 and the hostname message went away, and I can confirm the `Upgrade` message is gone. If no one objects, could we close this issue?

**Comment by TopherGopher** [comment] 2018-07-06 19:48
I found this issue mentioned (and apparently solved) over here: https://github.com/kubernetes-client/python/issues/526

`resp = kubernetes.stream.stream(self.core_api_instance.connect_get_namespaced_pod_exec, name,
namespace,command=exec_command1, stderr=True, stdin=False, stdout=True, tty=False)`

You can then manipulate that pipe using [the technique from the example code](https://github.com/kubernetes-client/python/blob/master/examples/exec.py#L61)

My issue is that I'm still getting an error message when I run it inside a pod in the cluster - 
```
>>> resp = k.stream.stream(k8s.connect_get_namespaced_pod_attach, 'datadog-agent-8pkwh', container="datadog-agent", namespace="default", stderr=True, stdin=False, stdout=True, tty=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 32, in stream
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 711, in connect_get_namespaced_pod_attach
    (data) = self.connect_get_namespaced_pod_attach_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 808, in connect_get_namespaced_pod_attach_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/stream/stream.py", line 27, in _intercept_request_call
    return ws_client.websocket_call(config, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/stream/ws_client.py", line 255, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: hostname '10.100.0.1' doesn't match either of 'ip-10-0-113-207.us-west-2.compute.internal', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local', '0e23207807f30610a20a7dc08f349bad.sk1.us-west-2.eks.amazonaws.com'
```
I'll let you know if I find the fix ;-)

**Comment by TopherGopher** [comment] 2018-07-06 19:48
The fix was I upgraded from Python 2 to Python 3 and the hostname message went away, and I can confirm the `Upgrade` message is gone. If no one objects, could we close this issue?

**Comment by scher200** [comment] 2018-08-06 14:18
for anyone ending up here Googling: **connect_get_namespaced_pod_attach "message":"Upgrade request required"**

**Comment by mpw07458** [comment] 2018-08-06 15:03
@scher200 you also need to upgrade the ssl on python to make it work, definitely you need kubernetes stream but thats one aspect you also need to upgrade SSL and on my mac its a bit complicated not sure about windows/linux

**Comment by scher200** [comment] 2018-08-06 18:42
here it worked out of the box with linux..

**Comment by mpw07458** [comment] 2018-08-06 19:27
the older openssl versions still cause this issue using Streams

type "openssl version"
I believe you need a version 1.X and above
the 0.98 and earlier versions fail with the same error with streams

I have
OpenSSL 1.0.2o  27 Mar 2018 and it works with streams
the 0.98 and earlier versions fail with the same error with streams

**Comment by avisrivastava254084** [comment] 2019-05-28 14:08
Even after applying all the standard configurations and examples, applying the solutions of @scher200 , I am getting a bad request.
My code:
```
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint
from kubernetes import client, config, stream
stream = stream.stream

# Configure API key authorization: BearerToken
configuration = kubernetes.client.Configuration()
configuration.host = "https://mine.eks.amazonaws.com"
configuration.verify_ssl = False
configuration.api_key['authorization'] = "my_token"
# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
configuration.api_key_prefix['authorization'] = 'Bearer'
configuration.debug = True

api_instance = kubernetes.client.CoreV1Api(
    kubernetes.client.ApiClient(configuration))
name = 'jupyter-aviral'  # str | name of the PodExecOptions
namespace = 'jhub'  # str | object name and auth scope, such as for teams and projects
# str | Command is the remote command to execute. argv array. Not executed within a shell. (optional)
command = 'echo "hail aviral"'
# bool | Redirect the standard error stream of the pod for this call. Defaults to true. (optional)
stderr = True
# bool | Redirect the standard input stream of the pod for this call. Defaults to false. (optional)
stdin = True
# bool | Redirect the standard output stream of the pod for this call. Defaults to true. (optional)
stdout = True
# bool | TTY if true indicates that a tty will be allocated for the exec call. Defaults to false. (optional)
tty = True

try:
    api_response = stream(api_instance.connect_post_namespaced_pod_exec(
        name, namespace, command=command, stderr=stderr, stdin=stdin, stdout=stdout, tty=tty)
    )
    pprint(api_response)
except ApiException as e:
    print("Exception when calling CoreV1Api->connect_post_namespaced_pod_exec: %s\n" % e)

```

The traceback is:
```
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2019-05-28 19:34:38,092 DEBUG Starting new HTTPS connection (1): 0d6fb20cb6b6acb7fbc1b2c264d5e9a1.yl4.ap-south-1.eks.amazonaws.com:443
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
send: b'POST /api/v1/namespaces/jhub/pods/jupyter-aviral/exec?command=echo+%22hail+aviral%22&stderr=True&stdin=True&stdout=True&tty=True HTTP/1.1\r\nHost: mine.eks.amazonaws.com\r\nAccept-Encoding: identity\r\nContent-Length: 0\r\nAccept: */*\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/9.0.0/python\r\nauthorization: Bearer my_api_token\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Audit-Id: 88df8863-61b1-4fe7-9d39-d0e6059ea993
header: Content-Type: application/json
header: Date: Tue, 28 May 2019 14:04:38 GMT
header: Content-Length: 139
2019-05-28 19:34:38,420 DEBUG https://mine.eks.amazonaws.com:443 "POST /api/v1/namespaces/jhub/pods/jupyter-ankita/exec?command=echo+%22hail+aviral%22&stderr=True&stdin=True&stdout=True&tty=True HTTP/1.1" 400 139
Exception when calling CoreV1Api->connect_post_namespaced_pod_exec: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '88df8863-61b1-4fe7-9d39-d0e6059ea993', 'Content-Type': 'application/json', 'Date': 'Tue, 28 May 2019 14:04:38 GMT', 'Content-Length': '139'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
```

**Closed** 2019-06-27 14:50 UTC
Labels: lifecycle/rotten

**Comment by Pega88** [comment] 2019-10-16 12:17
I'm having the same issue with a way more simpler setup:
`curl -H "Authorization: Bearer $TOKEN" --cacert $CACERT $K8S/api/v1/namespaces/devops/pods/spinnaker-spinnaker-halyard-0/exec?command=ls` I am getting the same response:
`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Upgrade request required",
  "reason": "BadRequest",
  "code": 400
}`

When I just ask for my pod details, it does work - so my Auth and Cert should be fine:
`curl -H "Authorization: Bearer $TOKEN" --cacert $CACERT $K8S/api/v1/namespaces/devops/pods/spinnaker-spinnaker-halyard-0/log` --> logs printing correctly.

**Comment by vennilashanthi** [comment] 2020-11-25 10:55
Hi all,
I am getting the same error which @Pega88 got. Is the issue resolved ? If so, could you please let me know how to get rid of this error ?

**Comment by z-koki** [comment] 2022-09-09 02:24
> I'm having the same issue with a way more simpler setup: `curl -H "Authorization: Bearer $TOKEN" --cacert $CACERT $K8S/api/v1/namespaces/devops/pods/spinnaker-spinnaker-halyard-0/exec?command=ls` I am getting the same response: `{ "kind": "Status", "apiVersion": "v1", "metadata": {
> 
> }, "status": "Failure", "message": "Upgrade request required", "reason": "BadRequest", "code": 400 }`
> 
> When I just ask for my pod details, it does work - so my Auth and Cert should be fine: `curl -H "Authorization: Bearer $TOKEN" --cacert $CACERT $K8S/api/v1/namespaces/devops/pods/spinnaker-spinnaker-halyard-0/log` --> logs printing correctly. Would like to /reopen

This is because a websocket connection is required if you want to exec into a pod. 
See [https://stackoverflow.com/questions/49250370/kubernetes-pod-exec-api-upgrade-request-required](url)
For convenience, you can use wscat or wssh instead. If you insist on using curl, these parameters worked for me:
`--include \
--no-buffer \
--header "Connection: Upgrade" \
--header "Upgrade: websocket" \
--header "Sec-WebSocket-Key: NVwjmQUcWCenfWu98asDmg==" \
--header "Sec-WebSocket-Version: 13" \`
