### ISSUE TITLE
watcher throws error exactly after 5 mins on Kubernetes 1.16

### ISSUE THREAD

**Issue by yuzisun** [kubernetes-client/python#1294] opened 2020-10-20 12:52 UTC
**What happened (please include outputs or screenshots)**:
Setup a watcher with listing pods in a namespace but it throws following error after exactly 5 minutes, this only happens when we upgrade to kubernetes 1.16, it works fine with Kubernetes 1.15. Tested with both client 11.0.0 and 12.0.0 versions and have the same issue.

```
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/urllib3/response.py", line 601, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/venv/lib/python3.7/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/venv/lib/python3.7/site-packages/urllib3/response.py", line 605, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    for event in w.stream(core.list_namespaced_pod, namespace='dsun'):
  File "/venv/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 163, in stream
    for line in iter_resp_lines(resp):
  File "/venv/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 56, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/venv/lib/python3.7/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/opt/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/venv/lib/python3.7/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**What you expected to happen**:
the watcher should keep running after 5 mins

**How to reproduce it (as minimally and precisely as possible)**:
Run this code and error is thrown after 5 mins. however if you do `core.list_namespace` that seems to work.
```
from kubernetes import client, config, watch
from functools import partial
# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

core = client.CoreV1Api()
count = 100000
w = watch.Watch()
for event in w.stream(core.list_namespaced_pod, namespace='default'):
    print(event)
    #print("Event: %s %s" % (event['type'], event['object'].metadata.name))
    count -= 1
    if not count:
        w.stop()

print("Ended.")
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 1.16
- OS (e.g., MacOS 10.13.6): 
- Python version (`python --version`): 3.7
- Python client version (`pip list | grep kubernetes`): both 11.0.0 and 12.0.0

**Comment by roycaihw** [comment] 2020-10-26 16:47
> Tested with both client 11.0.0 and 12.0.0 versions and have the same issue

It sounds like a server-side issue when you changed to 1.16. Do you see the same issue using kubectl?

**Comment by yuzisun** [comment] 2020-10-26 17:12
> > Tested with both client 11.0.0 and 12.0.0 versions and have the same issue
> 
> It sounds like a server-side issue when you changed to 1.16. Do you see the same issue using kubectl?

No, kubectl wait works fine if I set timeout to a longer time and does not exit after 5 minutes.

**Comment by yuzisun** [comment] 2020-10-27 15:27
@roycaihw Any thoughts?

**Comment by roycaihw** [comment] 2020-10-28 03:16
I couldn't reproduce the 5min behavior with 12.0.0 client and 1.16 server (python 3.8.5). I can reproduce the same error by letting the client establishing the watch and then killing the server. Doing the same to kubectl (with verbose logging), it prints `Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""`.

I think there are two issues: 
1. the python client should handle server closing connection and produce meaningful log
2. we need to verify if the original issue was caused by a closed connection (based on the description I still suspect it's a server-side timeout). If so, why was the connection closed / who set a timeout. 

To answer those question, first we need a better way to catch the event. So far I found everything happening within [resp.read_chunked](https://github.com/kubernetes-client/python-base/blob/2da2b981ca806b25487ad92d01a2164815c18517/watch/watch.py#L56), which isn't a good interface for us to catch & handle the event before it triggers `invalid literal for int`. We may need to explore options other than `read_chunked`. Also I found some low level workaround that looks related: https://github.com/psf/requests/issues/4248#issuecomment-408666274

**Comment by yuzisun** [comment] 2020-11-23 13:31
@roycaihw We actually put haproxy in front of the APIServer and disconnects for any idle connections after 5 minutes, looks like we need to handle the closing connection more gracefully.

**Comment by KeithTt** [comment] 2021-04-12 08:24
Got the same problem...but I only call the watch method by kube_config without any proxy.

Kube version: 1.16.4

I have four kubernetes clusters, only the two 1.16.4 clusters had this problem, I think it is a server side issue, but we will not update our kube cluster  in a short time.

Here is my code:
```python
with Elasticsearch(hosts=hosts, timeout=120) as es:
    if not es.indices.exists(index=index_today):
        es.indices.create(index=index_today)

    # Configs can be set in Configuration class directly or using helper utility
    config.load_kube_config(config_file=kube_config)
    v1 = client.CoreV1Api()
    w = watch.Watch()

    try:
        for event in w.stream(v1.list_event_for_all_namespaces):
            doc = {
                "cluster_name": cluster_name,
                "time_iso8601": arrow.Arrow.fromdatetime(event['object'].metadata.creation_timestamp).isoformat(),
                "namespace": event['object'].metadata.namespace,
                "type": event['object'].type,
                "reason": event['object'].reason,
                "message": event['object'].message
            }
            # print(json.dumps(doc))
            # if doc["type"] == "Warning":
            #     send_text('[ {} ]- {}'.format(cluster_name, doc["message"]))
            if es.exists(index=index_today, doc_type=index, id=event['object'].metadata.uid):
                continue
            es.create(index=index_today, doc_type=index, body=doc, id=event['object'].metadata.uid)
    except Exception as e:
        print(e)
```

I have checked the source code of `Watch.stream(func)`, I do not think I can catch the exception in the `for` loop.

So can we catch this exception by some method?

**Closed** 2021-05-12 08:25 UTC
Labels: kind/bug, lifecycle/rotten
