### ISSUE TITLE
How do I run kubectl apply-f using the API

### ISSUE THREAD

**Issue by moluzhui** [kubernetes-client/python#1168] opened 2020-05-19 12:04 UTC
I tried using the Kubernetes API python to execute the `kubect apply` command to deploy and update resources

the kubectl command is as follows:
```
kubectl apply -f export
```
`export` is a `folder` containing `multiple yaml files`, which is generated by `kompose convert -o export`

I only found an alternative API for `kubectl create`, but I didn't find `apply`

How do I implement `kubectl apply` to `create` resources and possible subsequent `updates`

If you know, please let me know. thank you in advance!

**Comment by Sunnykaby** [comment] 2020-05-20 06:02
maybe you can use replace_XXX api

**Comment by MoShitrit** [comment] 2020-05-21 05:02
You can look at that example as well https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py

**Comment by vishnu667** [comment] 2020-05-21 10:16
@MoShitrit create_from_yaml works when we have to create a resource.
Let's say I want to update an annotation or the image create_from_yaml fails with [FailToCreateError](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py#L165)

**Comment by vishnu667** [comment] 2020-05-21 12:13
Trying to write a utility [replace_from_yaml](https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py)
But am hitting the error.
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the name of the object (scheduler-deployment) does not match the name on the URL (airflow)",
  "reason": "BadRequest",
  "code": 400
}
```
The same payload works with `kubectl replace -f ` not sure what am missing.

**Comment by MoShitrit** [comment] 2020-05-21 23:10
> Trying to write a utility [replace_from_yaml](https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py)
> But am hitting the error.
> 
> ```
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {
>     
>   },
>   "status": "Failure",
>   "message": "the name of the object (scheduler-deployment) does not match the name on the URL (airflow)",
>   "reason": "BadRequest",
>   "code": 400
> }
> ```
> 
> The same payload works with `kubectl replace -f ` not sure what am missing.

What's the value of `kind` from this line, in the error you're getting?
https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py#L156

**Comment by vishnu667** [comment] 2020-05-22 07:13
This is the payload Am passing
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment_time: '2020-05-22 12:39:38.324272'
  labels:
    app: scheduler
  name: scheduler-deployment
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      annotations:
        deployment_time: '2020-05-22 12:39:38.324286'
      labels:
        app: scheduler
    spec:
      containers:
      - args:
        - scheduler
        env:
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: airflow
        image: airflow_base:local
        imagePullPolicy: IfNotPresent
        name: scheduler
      serviceAccountName: airflow-scheduler-serviceaccount
```
If you can point me in the right direction I might be able to write down both these functionalities replace and apply.

**Comment by MoShitrit** [comment] 2020-05-24 06:05
The payload seems fine. But looking back at your code, I think I see what's missing.
You'll need to add a `namespace` argument to the call you make here https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py#L157
and in order to make sure you always have a value (which would align with how `kubectl` does it, you'll need to add an `else` block [here](https://github.com/vishnu667/python/blob/replace_from_yaml/kubernetes/utils/replace_from_yaml.py#L149-L151) like this:
```python
else:
    namespace = "default"
```
`namespace` is a required parameter, and by the error message it seems like the function is trying to use `airflow` as the name of the deployment, rather than the namespace.
So I would try to be more explicit and see if it helps.

**Comment by roycaihw** [comment] 2020-06-08 23:04
kubectl implements a three-way diff logic to perform a client-side apply. We should add example/documentation about how to use the new server-side apply feature instead of re-implementing client-side apply in this client.

**Comment by vishnu667** [comment] 2020-06-19 23:43
@roycaihw  Can you point me to the kubectl implementation Let me see if I can code the same logic in python.

**Comment by vishnu667** [comment] 2020-06-19 23:59
@MoShitrit agree but for the yaml am providing am passing the namespace value.
Will add the else statement also.

**Comment by tvkit** [comment] 2020-10-03 23:00
> I tried using the Kubernetes API python to execute the `kubect apply` command to deploy and update resources
> 
> ```
> kubectl apply -f export
> ```
> 

Why would you want to do that?  :grin:

---

I'm using `ytt` to generate the config. It doesn't seem to have (or couldn't find) python integration.  So I'm using a shell wrapper to run the command.   [Here's a decent example for an arbitrary shell operation](https://code-maven.com/python-capture-stdout-stderr-exit). Essentially:

```
def run(cmd):
    proc = subprocess.Popen(cmd, stdout = subprocess.PIPE, stderr = subprocess.PIPE)
    stdout, stderr = proc.communicate()
    return proc.returncode, stdout, stderr
```


I'm caching the `ytt` output into temp file, and subsequently running the `kubectl` shell command you referenced. Not ideal, but it gets the job done providing `kubectl` is available within the shell.

**Comment by solarmosaic-kflorence** [comment] 2020-11-14 00:50
I'm not sure how people are using the python client without this feature... I'm trying to move our deployment process from command line tools (like `kubectl`) into a python lambda function and I'm surprised to find there is no easy way to replace a `kubectl apply -f` with a client call.

**Comment by tvkit** [comment] 2020-11-14 01:16
@solarmosaic-kflorence  ytt via python is a legit approach. It may not suit your peculiar needs, but it works well in our production environment, and is widely adopted method for transforming yaml files.

**Comment by solarmosaic-kflorence** [comment] 2020-11-16 17:18
@tvkit i'm sure it is, but it doesn't have a lot to do with the `apply` functionality that `kubectl` provides. And I'd rather not use python just to call a CLI command... kind of defeats the purpose of using python.

**Comment by solarmosaic-kflorence** [comment] 2020-11-16 17:22
This ticket may be a duplicate of https://github.com/kubernetes-client/python/issues/1093

**Closed** 2020-12-16 18:04 UTC
Labels: kind/documentation, lifecycle/rotten

**Comment by adammrozik** [comment] 2021-02-19 12:02
Hey! Is there any chance this would be implemented in the future? 

Not sure how to effectively mimic `kubectl apply` behaviour with current API

**Comment by robcxyz** [comment] 2022-04-04 09:52
@adammrozik - Looks like they just merged an example https://github.com/kubernetes-client/python/pull/1752/files

**Comment by Pithikos** [comment] 2023-01-07 17:47
Unfortunately it seems that only a rewrite of `kubectl`'s `apply` into Python will work.

A workaround can be something like below. But to make it omnipotent it will need much more logic

```
    KUBERNETES_ENTITIES = {
        'Service': {
            'client_class': kubernetes.client.CoreV1Api,
            'url_base': 'api/v1',
            'resource_name': 'services',
            'response_type': 'V1Service',
        },
        'StatefulSet': {
            'client_class': kubernetes.client.AppsV1Api,
            'url_base': 'apis/apps/v1',
            'resource_name': 'statefulsets',
            'response_type': 'V1StatefulSet',
        },
    }
    
   def apply_document(doc):
       #  NOTE: Only meant to be used for creating new resources, not updating existing ones
        kind = doc['kind']
        namespace = doc['metadata'].get('namespace', None)

        client = Kube.KUBERNETES_ENTITIES[kind]['client_class']()
        url_base = Kube.KUBERNETES_ENTITIES[kind]['url_base']
        resource = Kube.KUBERNETES_ENTITIES[kind]['resource_name']
        response_type = Kube.KUBERNETES_ENTITIES[kind]['response_type']

        if namespace is None:
            url = f'/{url_base}/{resource}'
        else:
            url = f'/{url_base}/namespaces/{namespace}/{resource}'

        return client.api_client.call_api(
            url, 
            'POST', 
            body=doc, 
            response_type=response_type,  # or use the generic 'object'
        )
```
