### ISSUE TITLE
Hey I need to write the client for kubectl plugin, is there any doc that how can I do it through this python client?

### ISSUE THREAD

**Issue by mukhtar-inamdar** [kubernetes-client/python#1823] opened 2022-06-07 12:36 UTC
**Hey I need to write the client for kubectl plugin, is there any doc that how can I do it through this python client?**:

**Comment by Akasurde** [comment] 2022-06-30 08:40
@mukhtar-inamdar Thanks for reporting this issue. Could you please refer https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/ ? Thanks.

**Comment by roycaihw** [comment] 2022-08-01 16:43
This seems like a duplicate of #1822
/close

**Closed by roycaihw** 2022-08-01 16:43 UTC
Labels: kind/documentation
