### ISSUE TITLE
Problem with python 3.7 and "async" as parameter name

### ISSUE THREAD

**Issue by amoralej** [kubernetes-client/python#558] opened 2018-06-28 09:15 UTC
In python 3.7, async is a reserved keyword [1]. This module is using async as parameter name in different methods and it's failing with syntax errors like (excerpt):

  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/admissionregistration_api.py", line 120
    async=params.get('async'),
        ^
SyntaxError: invalid syntax

byte-compiling /tmp/test/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/storage_v1alpha1_api.py to storage_v1alpha1_api.cpython-37.pyc
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/storage_v1alpha1_api.py", line 132
    async=params.get('async'),
        ^
SyntaxError: invalid syntax

byte-compiling /tmp/test/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/autoscaling_api.py to autoscaling_api.cpython-37.pyc
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/autoscaling_api.py", line 120
    async=params.get('async'),
        ^
SyntaxError: invalid syntax

Note that python 3.7 was released recently and some distros (as fedora) will be switching to it.

[1] https://docs.python.org/3.7/whatsnew/3.7.html#summary-release-highlights

**Comment by hroncok** [comment] 2018-06-28 10:50
Note that Fedora **already is** switching to Python 3.7.

**Comment by hroncok** [comment] 2018-06-28 10:55
It appears that async is part of the API which makes things hard to fix juts by renaming. I have a decorator that might be useful for this (consider it Public Domain or CC0):

```python
from functools import wraps


def deprecated_async(func):
    """A decorator, that let's us keep our old API, but deprecate it"""
    @wraps(func)
    def inner(*args, **kwargs):
        if 'async' in kwargs:
            if 'asynchronous' in kwargs:
                raise ValueError('cannot use both async and asynchronous '
                                 'keyword arguments! the latter obsoletes the first.')
            warnings.warn('async keyword argumnt is deprecated, '
                          'use asynchronous instead', DeprecationWarning)
            kwargs['asynchronous'] = kwargs.pop('async')
        return func(*args, **kwargs)
    return inner


@deprecated_async
def awesome_func(foo, bar, asynchronous=False):
    """People can pass async or asynchronous"""
    ...
```

**Comment by tomplus** [comment] 2018-06-28 11:01
OMG, it looks like a breaking change, btw this part is generated by swagger-codegen.

What does it mean "fedora is switching to p37" ?

**Comment by hroncok** [comment] 2018-06-28 11:03
> What does it mean "fedora is switching to p37" ?

https://fedoraproject.org/wiki/Changes/Python3.7

**Comment by tomplus** [comment] 2018-06-28 14:10
Thanks @hroncok , so Fedora 29 will use it. I though that latest version was switched or something ;)

**Comment by hroncok** [comment] 2018-06-28 14:13
But Fedora 29 already needs to use it at this point. From user perspective, this is something form the future, but from ours, it's the current one.

**Comment by Chekov2k** [comment] 2018-07-02 11:37
Since Homebrew updated Python to 3.7, my workaround for the Ansible OpenShift and Kubernetes integration was to run this little sed command in the kubernetes/openshift python module directory:
```
cd /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kubernetes
find . -name "*.py" | xargs sed -i '' s/async=para/async_=para/g
cd /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openshift
find . -name "*.py" | xargs sed -i '' s/async=para/async_=para/g
```
Hope it helps someone until the issue is fixed properly

**Comment by jbiel** [comment] 2018-07-02 15:12
I ran into this after Homebrew updated Python to 3.7 this morning. @Chekov2k, how are you installing the Kubernetes python package to that directory? If I do a `pip install` it fails (due to this issue) and `kubernetes` isn't present in `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages`.

**Comment by Chekov2k** [comment] 2018-07-02 17:03
@jbiel I just ran pip3 install kubernetes openshift with a clean install of python3 beforehand

**Comment by jbiel** [comment] 2018-07-03 22:18
Thanks @Chekov2k. I ended up using this:

```
find /usr/local/lib/python3.7/site-packages/kubernetes/	 -name "*.py" | xargs sudo sed -i 's/async=/async_=/g'
sudo sed -i 's/if not async:/if not async_:/' /usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py
```

**Comment by tomplus** [comment] 2018-07-08 00:45
I opened PR in [swagger-codegen](https://github.com/swagger-api/swagger-codegen/pull/8401) and added a simple workaround to [gen](https://github.com/kubernetes-client/gen/pull/67) repository. Next release should support Python 3.7.

If you can't wait I suggest running

```
find "${OUTPUT_DIR}/client/" -type f -name \*.py -exec sed -i 's/async=/async_req=/g' {} +
find "${OUTPUT_DIR}/client/" -type f -name \*.py -exec sed -i 's/async bool/async_req bool/g' {} +
find "${OUTPUT_DIR}/client/" -type f -name \*.py -exec sed -i "s/'async'/'async_req'/g" {} +
sed -i "s/if not async/if not async_req/g" "${OUTPUT_DIR}/client/api_client.py"
```

where OUTPUT_DIR is the path to the library.

**Comment by roycaihw** [comment] 2018-07-27 22:37
Closing as new releases have been generated using https://github.com/kubernetes-client/gen/pull/67

**Closed by roycaihw** 2018-07-27 22:37 UTC

**Comment by JccSanabria** [comment] 2019-11-09 14:39
Fixed up replacing just the inputs and regular attributes named async (not the _async) within the null.py file.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/8854990/68530246-2f21e580-02dd-11ea-8957-c9df3c84b839.png">
