### ISSUE TITLE
Update urlib3 package version and use new methods

### ISSUE THREAD

**Issue by leonp-c** [kubernetes-client/python#2259] opened 2024-08-04 15:51 UTC
urlib3 is showing deprecation warning for new versions:
```
kubernetes/client/rest.py:44: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
    return self.urllib3_response.getheaders()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

```

Please update to latest urlib3 and use the suggested methods

**Comment by varuzam** [comment] 2024-08-09 19:11
https://github.com/kubernetes-client/python/issues/2101

**Comment by roycaihw** [comment] 2024-08-14 20:14
Closing as duplicate of https://github.com/kubernetes-client/python/issues/2101

**Closed by roycaihw** 2024-08-14 20:14 UTC
Labels: kind/feature
