### ISSUE TITLE
Error 403 forbidden issue when i ran celery task which reading kubernetes api

### ISSUE THREAD

**Issue by Deepakchawla** [kubernetes-client/python#1045] opened 2019-12-30 12:14 UTC
What we are doing?

we deployed our Django application on Kubernetes has some task to create some pods on Kubernetes using Kubernetes python API but when I am calling the API from application then it is working properly but when I am reading the pod details using read_namaspace_deployment then it is giving us following issue and we give all permission to the app pod but even getting the issue...

> kubernetes.client.rest.ApiException: (403)
> Reason: Forbidden
> HTTP response headers: HTTPHeaderDict({'Audit-Id': 'd7995c4f-8d44-4f89-bea9-0cb6a0391704', 'Content-Type': 'application/json', 'Date': 'Sun, 29 Dec 2019 12:38:51 GMT', 'Content-Length': '282'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.extensions "nfs-provisioner-pod-demo-f5125cca9" Forbidden","reason":"NotFound","details":{"name":"nfs-provisioner-pod-demo-f5125cca9","group":"extensions","kind":"deployments"},"code":403}

**Comment by palnabarun** [comment] 2020-01-06 17:47
Potential duplicate of #1046 

Closing it for now. Please reopen if you feel otherwise.

/close

**Closed by palnabarun** 2020-01-06 17:47 UTC
Labels: kind/bug
