### ISSUE TITLE
list_api_service:  ValueError: Invalid value for `service`, must not be `None`

### ISSUE THREAD

**Issue by clausa20** [kubernetes-client/python#1174] opened 2020-05-29 14:41 UTC
Hello,
I try to get apiservice using in python doing:

```
config.load_kube_config(kubectl_config_full_path)
api_instance = client.ApiregistrationV1Api()
response = api_instance.list_api_service()
print("Api services: " + str(response))
```
but I get the following error:

**ValueError: Invalid value for `service`, must not be `None`**

I have a AWS EKS 1.15 as Kubernetes Master.
Python 3.6.8.
python kubernetes client 10.0.0
Ubuntu 16.04.6 LTS 

**Update:**
I've tested it with python kubernetes client 11.0.0 and I get the same error

**Comment by MoShitrit** [comment] 2020-05-29 16:56
I was able to reproduce it locally.
I'll take a look at the code and figure out what needs to be done.
/assign

**Comment by MoShitrit** [comment] 2020-05-31 18:27
@clausa20 I've started looking into it, and for now I have workaround on how to make this work without failing.
If you add `_preload_content=False` as a kwarg to your function call, you can then get the list using `response.data`, as following:

```python
    kubernetes.config.load_kube_config()
    api_registration_api = kubernetes.client.ApiregistrationV1Api()
    response = api_registration_api.list_api_service(_preload_content=False)
    print(response.data)
```

I'll keep looking into why the data serialization fails and figure out if this it's an intended behavior or something that requires fixing and will act accordingly. But I hope that I was able to get you unblocked for now.

**Comment by clausa20** [comment] 2020-06-01 19:25
@MoShitrit thanks for the workaround, it fits ok for me. Regards.

**Comment by roycaihw** [comment] 2020-06-09 00:42
Looks like this is another occurrence of https://github.com/kubernetes-client/gen/issues/52 and has been fixed by https://github.com/kubernetes/kubernetes/pull/85728 in Kubernetes 1.18. Kubernetes sometimes incorrectly restricts a field to be required but the apiserver may omits the field in real responses. These responses break the generated clients since the generated client-side validation expects the required field to exist. 

For now the workaround is either to avoid de-serializing the response so the client-side validation doesn't kick in, or to remove the client-side validation if you have access to your local module code. Once we cut a new release with the 1.18 openapi spec, the generated client won't expect the field to be required.

**Closed** 2020-11-06 02:12 UTC
Labels: kind/bug, lifecycle/rotten
