### ISSUE TITLE
Markdown docs are too large for Github

### ISSUE THREAD

**Issue by alop** [kubernetes-client/python#1642] opened 2021-12-01 20:46 UTC
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod

**Description of the issue (please include outputs or screenshots if possible)**:
The Markdown files are too large for GitHub to display them properly, you just get a "sorry" message. This makes reading them very difficult.

**Comment by micw523** [comment] 2021-12-03 01:49
This is a duplicate of #1557

I'll close this for now in favor of the existing issue.

/close

**Closed by micw523** 2021-12-03 01:49 UTC
Labels: kind/documentation
